### PR TITLE
upgrade airflow to 1.10.12

### PR DESCRIPTION
**Pull request by jay-bhambhani**

### CODE REVIEW

**Review by devstein — COMMENTED** [review]
Did you check the upstream [repo](https://github.com/puckel/docker-airflow)? It looks like its unmaintained, but there might be relevant information in the open issues and PRs

**Comment by jay-bhambhani** [comment]
its bad. i dont think they've upgraded beyond 1.10.9, so we cant upgrade to the latest helm chart. this branch has what we want, but should we use the branch? https://github.com/puckel/docker-airflow/pull/576. maybe the best bet is rebase on another fork?

**Comment by devstein** [comment]
Oh @jay-bhambhani why do we use the `docker-airflow` repo if there exists a public image? https://hub.docker.com/r/apache/airflow/dockerfile

@jpugliesi Set this up, so he would know

**Comment by jay-bhambhani** [comment]
i think it was becuase of the helm chart. now we dont have a choice in the matter https://github.com/helm/charts/blob/master/stable/airflow/UPGRADE.md#v6xx--v700

**Comment by jay-bhambhani** [comment]
going to close this and will create new pr for change

**Pull request closed without merging**
